target = 'libtsload'

Import('env')

lib = env.Clone()

lib.AddDeps(('lib', 'libjson'), 
            ('lib', 'libtscommon'), 
            ('lib', 'libhostinfo'))

objects = lib.CompileSharedLibrary(Glob("src/disp/*.c"))
library = lib.LinkSharedLibrary(target, objects)

lib.InstallTarget(lib['INSTALL_LIB'], library)