target = 'libtsload'

Import('env')

lib = env.Clone()

if lib.SupportedPlatform('posix'):
    lib.Append(LIBS = ['c'])

lib.AddDeps(('lib', 'libjson'), 
            ('lib', 'libtscommon'), 
            ('lib', 'libtsagent'),
            ('lib', 'libhostinfo'))

objects = lib.CompileSharedLibrary(Glob("src/disp/*.c"))
library = lib.LinkSharedLibrary(target, objects)