target = 'lib/libhostinfo'

Import('env')

lib = env.Clone()

lib.PreparePlatform()

lib.AddDeps(('lib', 'libjson'), ('lib', 'libtscommon'))
env['DEPTARGETS'][target] = lib.SharedLibrary(lib.Target(target), Glob("plat/*/*.c"))