target = 'libhostinfo'

Import('env')

lib = env.Clone()

lib.PreparePlatform()

if lib.SupportedPlatform('solaris'):
    lib.Append(LIBS = ['diskmgt', 'lgrp', 'nvpair', 'kstat', 'picl'])
if lib.SupportedPlatform('win'):
    lib.Append(LIBS = ['setupapi'])

lib.AddDeps(('lib', 'libjson'), ('lib', 'libtscommon'))

objects = lib.CompileSharedLibrary()
library = lib.LinkSharedLibrary(target, objects)

lib.InstallTarget(lib['INSTALL_LIB'], library)