target = 'lib/libjson'

Import('env')

lib = env.Clone(LIBS = ['stdc++'],
                CXXFLAGS = ['-Os', '-ffast-math', '-DJSON_LESS_MEMORY'])

env['DEPTARGETS'][target] = lib.SharedLibrary(lib.Target(target), Glob("src/*.cpp"))