import os

tgtdir = 'bin'
target = 'mpbench'

Import('env')

cmd = env.Clone()

if cmd.SupportedPlatform('posix'):
    cmd.Append(LIBS = ['c'])

cmd.AddDeps(('lib', 'libtscommon'),
            ('lib', 'libjson'))
mpbench = cmd.Program(cmd.Target(tgtdir, target), Glob("*.c"))