target = 'libtsagent'

Import('env')

lib = env.Clone()

# Add winsock2 library
if lib.SupportedPlatform('win'):
    lib.Append(LIBS = ['Ws2_32'])

# Sockets and name services requires libraries
if lib.SupportedPlatform('solaris'):
    lib.Append(LIBS = ['socket', 'nsl'])


lib.PreparePlatform()
lib.AddDeps(('lib', 'libjson'), ('lib', 'libtscommon'))

objects = lib.CompileSharedLibrary()
library = lib.LinkSharedLibrary(target, objects)

lib.InstallTarget(lib['INSTALL_LIB'], library)