tgtdir = 'lib'
target = 'libtsagent'

Import('env')

lib = env.Clone()

if lib.SupportedPlatform('posix'):
    lib.Append(LIBS = ['c'])

if lib.SupportedPlatform('win'):
    lib.Append(LIBS = ['Ws2_32'])

if lib.SupportedPlatform('solaris'):
    lib.Append(LIBS = ['socket', 'nsl'])


lib.PreparePlatform()

lib.AddDeps(('lib', 'libjson'), ('lib', 'libtscommon'), ('lib', 'libhostinfo'))
env['DEPTARGETS'][target] = lib.SharedLibrary(lib.Target(tgtdir, target), Glob("src/*.c") + Glob("plat/*/*.c"))