from pathutil import *

target = 'swat-import'

Import('env')

cmd = env.Clone()

cmd.Append(LIBS = ['z', 'm'])

cmd.AddDeps(('lib', 'libtscommon'), 
            ('lib', 'libjson'))
objects = cmd.CompileProgram()
swat_import = cmd.Program(target, objects)

cmd.InstallTarget(cmd['INSTALL_BIN'], swat_import)

    