all: $(TARGSRC)  $(OBJDIR) $(TARGET)

$(OBJDIR):
	mkdir -p $@

$(TARGET): $(OBJDIR) $(TARGOBJDIRS) $(TARGOBJ) $(TARGEXTRAS)
	$(CC) -o $(BUILDDIR)/$(TARGETFILE) $(TARGOBJ) $(LDFLAGS)

$(EXTRAS_DIR)/%: % 
	cp $< $@

$(OBJDIR)/%/:
	mkdir -p $@

$(OBJDIR)/%.o: $(SRCDIR)/%.c
	$(CC) $(CFLAGS) -c $< -o $@

$(OBJDIR)/%.o: $(SRCDIR)/%.cpp 
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm $(TARGOBJ)
	rm -rf $(OBJDIR)