CC = /usr/bin/gcc

TARGETDIR = $(basename $(notdir $(TARGET)))
SRCDIR = src
INCDIR = include
BUILDDIR = ../../build
OBJDIR = $(BUILDDIR)/obj/$(TARGETDIR)

EXEC_CFLAGS = 
EXEC_CXXFLAGS = 
EXEC_LDFLAGS = 

SHARED_CFLAGS = -fPIC
SHARED_CXXFLAGS = -fPIC
SHARED_LDFLAGS = -shared

MODULE_CFLAGS = $(SHARED_CFLAGS) -I../../lib/libtsload/include
MODULE_CXXFLAGS = 
MODULE_LDFLAGS = $(SHARED_LDFLAGS) -ltsload

CFLAGS = -m64 -Wall -I$(INCDIR) $($(TYPE)_CFLAGS)
CXXFLAGS = $(CFLAGS) $($(TYPE)_CXXFLAGS)
LDFLAGS = -L$(BUILDDIR)/lib $($(TYPE)_LDFLAGS)

# For debugging
CFLAGS += -g

TARGSRC = $(addprefix $(SRCDIR)/,$(SRC))
TARGOBJ = $(addprefix $(OBJDIR)/,$(OBJ))
	