CC = /usr/bin/gcc

TARGETDIR = $(basename $(notdir $(TARGET)))
SRCDIR = src
INCDIR = include
BUILDDIR = ../../build
OBJDIR = $(BUILDDIR)/obj/$(TARGETDIR)

INCTSLOAD = -I../../lib/libtsload/include
INCJSON	= -I../../lib/libjson/include

LINKTSLOAD = -ltsload
LINKJSON = -ljson

EXEC_CFLAGS = 
EXEC_CXXFLAGS = 
EXEC_LDFLAGS = 

SHARED_CFLAGS = -fPIC
SHARED_CXXFLAGS = -fPIC
SHARED_LDFLAGS = -shared

MODULE_CFLAGS = $(SHARED_CFLAGS) $(INCTSLOAD) -DNO_JSON
MODULE_CXXFLAGS = 
MODULE_LDFLAGS = $(SHARED_LDFLAGS) $(LINKTSLOAD)

CFLAGS = -m64 -Wall -I$(INCDIR) $($(TYPE)_CFLAGS) -DJSON_DEBUG
CXXFLAGS = $(CFLAGS) $($(TYPE)_CXXFLAGS)
LDFLAGS = -L$(BUILDDIR)/lib $($(TYPE)_LDFLAGS)

# For debugging
CFLAGS += -g

TARGSRC = $(addprefix $(SRCDIR)/,$(SRC))
TARGOBJ = $(addprefix $(OBJDIR)/,$(OBJ))
	