import os

target = 'jsontsbench'

Import('env')

cmd = env.Clone()

if cmd.SupportedPlatform('posix'):
    cmd.Append(LIBS = ['c'])

cmd.AddDeps(('lib', 'libtscommon'),
            ('lib', 'libjson'),
            ('lib', 'libtsagent'))

objects = cmd.CompileProgram(Glob("*.c"))
jsontsbench = cmd.Program(target, objects)

cmd.InstallTarget(cmd['INSTALL_BIN'], jsontsbench)