import os

tgtdir = 'bin'
target = 'tsloadd'

Import('env')

cmd = env.Clone()

if cmd.SupportedPlatform('posix'):
    cmd.Append(LIBS = ['c'])

cmd.AddDeps(('lib', 'libtsagent'), 
            ('lib', 'libtscommon'), 
            ('lib', 'libjson'), 
            ('lib', 'libhostinfo'), 
            ('lib', 'libtsload'))
objects = cmd.CompileProgram()
tsloadd = cmd.Program(cmd.Target(tgtdir, target), objects)

cmd.Depends(tsloadd, 'tsload.cfg')
cmd.InstallFile('etc', 'tsload.cfg')