import os

tgtdir = 'bin'
target = 'run-tsload'

Import('env')

cmd = env.Clone()

if cmd.SupportedPlatform('posix'):
    cmd.Append(LIBS = ['c'])

cmd.AddDeps(('lib', 'libtsagent'), 
            ('lib', 'libtscommon'), 
            ('lib', 'libjson'), 
            ('lib', 'libhostinfo'), 
            ('lib', 'libtsload'))
objects = cmd.CompileProgram()
run_tsload = cmd.Program(cmd.Target(tgtdir, target), objects)

# Install test experiment files
for file in Dir('test').glob('*'):
    cmd.Depends(run_tsload,  file)
    cmd.InstallFile('share/run-tsload', file)