target = 'libtscommon'

Import('env')

lib = env.Clone()

# dl for modules
# pthread for thread-handling
if lib.SupportedPlatform('posix'):
    lib.Append(LIBS = ['dl', 'pthread'])

# We need librt for ns-precision time source
if lib.SupportedPlatform('linux'):
    lib.Append(LIBS = ['rt'])

# Process PLATAPIs
lib.PreparePlatform()

lib.AddDeps(('lib', 'libjson'))

objects = lib.CompileSharedLibrary()
library = lib.LinkSharedLibrary(target, objects)

lib.InstallTarget(lib['INSTALL_LIB'], library)