target = 'lib/libtscommon'

Import('env')

lib = env.Clone(LIBS = ['c', 'dl', 'pthread'])

lib.PreparePlatform()

lib.AddDeps(('lib', 'libjson'))
env['DEPTARGETS'][target] = lib.SharedLibrary(lib.Target(target), Glob("src/*.c") + Glob("plat/*/*.c"))