tgtdir = 'lib'
target = 'libtscommon'

Import('env')

lib = env.Clone()

if lib.SupportedPlatform('posix'):
    lib.Append(LIBS = ['c', 'dl', 'pthread'])

lib.PreparePlatform()

lib.AddDeps(('lib', 'libjson'))
env['DEPTARGETS'][target] = lib.SharedLibrary(lib.Target(tgtdir, target), Glob("src/*.c") + Glob("plat/*/*.c"))